service: serverless-person-service

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  environment:
    REGION: eu-west-1
    PERSON_TABLE: ${self:custom.stage}-person

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  createPerson:
    handler: createPerson/createPerson.main
    events:
      - http:
          path: person/create
          method: post

resources:
  - ${file(resources/dynamodb-table.yml)}
