service: serverless-person-service

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-lift

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  environment:
    REGION: eu-west-1
    PERSON_TABLE: ${self:custom.stage}-person
  iam:
    role:
      name: lambdaDynamoDbAccessRole
      path: /
      Version: "2012-10-17"
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:BatchGet*"
            - "dynamodb:DescribeStream"
            - "dynamodb:DescribeTable"
            - "dynamodb:Get*"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:BatchWrite*"
            - "dynamodb:CreateTable"
            - "dynamodb:Delete*"
            - "dynamodb:Update*"
            - "dynamodb:PutItem"
          Resource: "arn:aws:dynamodb:*:*:table/${self:custom.stage}-person"

custom:
  stage: ${opt:stage, self:provider.stage}

constructs:
  jobs:
    type: queue
    worker:
      handler: queue/queueHandler.main

functions:
  createPerson:
    handler: createPerson/createPerson.main
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
    events:
      - http:
          path: person/create
          method: post

resources:
  - ${file(resources/dynamodb-table.yml)}
